# This file was generated by GoReleaser. DO NOT EDIT.
cask "deployboard" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "91cedcda58ded22190e3cb364dbac9c2ac25e420a2db37b463083c28f8a68244"
      url "https://github.com/francistse/deployboard/releases/download/v#{version}/deployboard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a1cd790f3e064451bfe97112e6ea2e527494669d87b02a9dc74983db472c4ef"
      url "https://github.com/francistse/deployboard/releases/download/v#{version}/deployboard_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "deployboard"
  desc "Visual control console for your own macOS launchd deployments"
  homepage "https://github.com/francistse/deployboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deployboard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deployboard"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Deployboard serves a localhost dashboard (default http://127.0.0.1:9410).

    To run it as a LaunchAgent with KeepAlive (recommended), use the install
    script from the repo after brew install, or:
      deployboard --port 9410

    To enable Telegram alerts, store the bot token in the macOS Keychain:
      security add-generic-password -U -s deployboard-telegram -a bot_token -w "$TOKEN" -T /usr/bin/security

    Do not install RoboZephyr/tap/launch-pilot — that is upstream, not Deployboard.
  EOS
end
